name: Upload to S3

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world from dev!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build dev,
          echo test, and deploy your project dev.
